defaults: &defaults
  rotten_tomoatoes:
    key: ys5mave4hz6nw9d8ub6vac4u
  facebook:
   id: ENV['FACEBOOK_ID']
   secret: ENV['FACEBOOK_SECRET']
  s3:
   access_key_id: AKIAJPLRKC2UNCXX2RSQ
   secret_access_key: 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

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
