---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: staging
  domain: kudoso.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-b0be3a4c
  image_type: t2.micro
  image_id: ami-dc5e75b4
  security_groups:
  - default
  - web
  - web_tools
  external_host: ec2-52-1-129-101.compute-1.amazonaws.com
  external_ip: 52.1.129.101
  internal_host: ip-172-31-28-83.ec2.internal
  internal_ip: 172.31.28.83
  zone: us-east-1b
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}