---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app-e1a-01
  domain: kudoso.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-11755bec
  image_type: m3.medium
  image_id: ami-dc5e75b4
  security_groups:
  - default
  - web
  - web_tools
  external_host: ec2-52-6-128-179.compute-1.amazonaws.com
  external_ip: 52.6.128.179
  internal_host: ip-172-31-1-240.ec2.internal
  internal_ip: 172.31.1.240
  zone: us-east-1a
  provider: aws
  platform: linux
  root_device_type: ebs
  static_ip: 52.6.128.179
- volumes: {}
  static_ips:
    app-e1a-01: 52.6.128.179