graylog_server_version: "0.90.0"
graylog_server_prefix: "/usr/local"
graylog_server_dir: "#{graylog_server_prefix}/graylog2-server-#{graylog_server_version}"
graylog_server_pid_file: "/var/run/graylog-server.pid"
graylog_server_port: 12201
graylog_server_syslog_port: 12514

graylog_web_version: "0.90.0"
graylog_web_prefix: "/usr/local"
graylog_web_dir: "#{graylog_web_prefix}/graylog2-web-interface-#{graylog_web_version}"
graylog_web_pid_file: "/var/run/graylog-web.pid"
graylog_web_port: 9000

graylog_web_username: admin
graylog_web_password: admin1

graylog_mongo_database: graylog2
graylog_elasticsearch_index: "graylog2_#{Rubber.env}"

web_tools_proxies:
  graylog:
    role: graylog_web
    port: "#{graylog_web_port}"
    path: /
  graylog_server_api_browser:
    role: graylog_server
    port: 12900
    path: /api-browser/

role_dependencies:
  graylog_server: [graylog_mongodb, graylog_elasticsearch]
  graylog_mongodb: [mongodb]
  graylog_elasticsearch: [elasticsearch]

roles:
  graylog_server:
    packages: [openjdk-7-jdk, mongodb-10gen]
  graylog_web:
    packages: [openjdk-7-jdk]

# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graylog_server_secret: c9ca9862f8717075c67a402aa31397dd262cfd4f4e98c5d9ff1b12b882a2912a34573881cf1f007e43ae4240ad390a47313122fb5ab9f89beb70744beb9201198e15e18411f6bdf91d008f2eb6848e80364fd20f704bca8ce8c5b6e50512bda0

# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graylog_web_secret: 3988550ac0f120adc8967dfea3c1809fe03cdda268275345aa58e882f143b98e8fbe4d77066a00c73a3270c1aaf2125dc8f245a6c7fb71b2fb826e3e9727b12765c84ff33030b0084a8a68735d0d469a758bf0abfb21be4a24d74f0e4a6fb495